apiVersion: v1
kind: Service
metadata:
  name: helmpocapp-service
  namespace: helmpocappns
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: helmpocapp
spec:
  type: {{ .Values.service.type }} #LoadBalancer
  ports:
  - port: {{ .Values.service.port }} #8081
    targetPort: {{ .Values.service.targetPort }} #5000
  selector:
    app: helmpocapp
