apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: helmpocappns
  name: helmpocapp-deployment
spec:
  selector:
    matchLabels:
      app: helmpocapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%    
  template:
    metadata:
      labels:
        app: helmpocapp      
    spec:
      containers:
      - name: helmpocappcont
        image: helmpocsau.azurecr.io/helmpoc:v1
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 0.25     
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: helmpocapp
  namespace: helmpocappns
  name: helmpocapp-service
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 5000
  selector:
    app: helmpocapp
